// <auto-generated />
using System;
using DAL.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240712115256_ChangeUserEmailToEmailIntoBooking")]
    partial class ChangeUserEmailToEmailIntoBooking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3b62472e-4f66-49fa-a20f-e7685b9565d8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "38bd9dec-d40e-4b4c-85c3-05477bc1a607",
                            CreateOn = new DateTime(2024, 7, 12, 14, 52, 55, 848, DateTimeKind.Local).AddTicks(5342),
                            Email = "my@email.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MY@EMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEGxd3s8XvK6rGlqCcVyedPGDdIaW3iUWwzWVG7iy3v/MyL1KR72QALGInwQrFcpeJA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "86d55f40-9544-4d92-aa24-cc5693a5fd96",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ad7a9fd7-783a-4cb6-9db9-67a798b101f4",
                            CreateOn = new DateTime(2024, 7, 12, 14, 52, 55, 905, DateTimeKind.Local).AddTicks(8760),
                            Email = "moderator@email.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MODERATOR@EMAIL.COM",
                            NormalizedUserName = "MODERATOR",
                            PasswordHash = "AQAAAAIAAYagAAAAEISufKxRke5l0dL1KxzGIlvenVW9Pp8onBmSQ6xJyudcidM2y2d0QgZt4hz1vJOEyQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "moderator"
                        });
                });

            modelBuilder.Entity("DAL.Domain.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c07ada61-d847-43eb-b2eb-8e32adcd64f4"),
                            Name = "Букин Генадий"
                        },
                        new
                        {
                            Id = new Guid("ff9b30ce-ad2e-48ce-b811-e45481b55043"),
                            Name = "Жафаров Ильнур"
                        },
                        new
                        {
                            Id = new Guid("0bf3eaaa-107f-434e-85bc-49653b07515a"),
                            Name = "Неизвестный автор"
                        },
                        new
                        {
                            Id = new Guid("bb1a20f6-4406-4fe3-bf82-b3b31453667b"),
                            Name = "Стивен Кинг"
                        },
                        new
                        {
                            Id = new Guid("a6ffa373-2b5a-424e-b5ed-835678fd0d92"),
                            Name = "Джордж Оруэл"
                        },
                        new
                        {
                            Id = new Guid("ebcbdb38-9d81-4cba-9f6b-b0edb5d6bffa"),
                            Name = "Уильям Голдинг"
                        },
                        new
                        {
                            Id = new Guid("e5c68c75-9b15-4424-b062-b91c7f4b6332"),
                            Name = "Габриэль Гарсиа"
                        },
                        new
                        {
                            Id = new Guid("4f91476b-4021-4581-b729-78c8fede5d3f"),
                            Name = "Дмитрий Глуховский"
                        },
                        new
                        {
                            Id = new Guid("9c37a892-1e81-4120-b8be-de6833215e67"),
                            Name = "Василий Орехов"
                        },
                        new
                        {
                            Id = new Guid("d695cfa5-04cd-40ac-b0d7-307a8a876860"),
                            Name = "Андрей Левицкий"
                        },
                        new
                        {
                            Id = new Guid("30254b73-712a-48d4-bf0b-412216a90ade"),
                            Name = "Вячеслав Шалыгин"
                        },
                        new
                        {
                            Id = new Guid("fa10b14c-e352-4eac-91ae-982cb3fd3982"),
                            Name = "Роман Глушков"
                        },
                        new
                        {
                            Id = new Guid("33a9c3e4-be82-40dd-8c06-4f29b0ac732a"),
                            Name = "Захар Петров"
                        },
                        new
                        {
                            Id = new Guid("2acdaae8-d1ce-4995-bc07-537f77cc74bc"),
                            Name = "Айн Рэнд"
                        },
                        new
                        {
                            Id = new Guid("afe48adb-b2a8-4d40-aef2-2816ec837304"),
                            Name = "Валентин Катаев"
                        },
                        new
                        {
                            Id = new Guid("a40e7075-54fc-4015-9488-1b32652b96e4"),
                            Name = "Олдос Хаксли"
                        },
                        new
                        {
                            Id = new Guid("7785baef-d027-4c00-be4f-237846c9c318"),
                            Name = "Артур Конан Дойл"
                        },
                        new
                        {
                            Id = new Guid("65b1fd9e-36d4-4965-bd3f-66a3e4859426"),
                            Name = "Наиль Выборнов"
                        },
                        new
                        {
                            Id = new Guid("ee09b74a-99ff-4f41-a04b-5957c2d8c3b6"),
                            Name = "Эрих Мария Ремарк"
                        },
                        new
                        {
                            Id = new Guid("1198ab8d-59e8-4ce8-a4ee-98cce1f65eec"),
                            Name = "Рей Брэдбери"
                        },
                        new
                        {
                            Id = new Guid("3cbe84ba-9744-4cef-9dd9-815c7c53e133"),
                            Name = "Сергей Лукьяненко"
                        },
                        new
                        {
                            Id = new Guid("3f40c815-4d3f-42f7-92e8-10543306465f"),
                            Name = "Алексей Гришин"
                        },
                        new
                        {
                            Id = new Guid("549ceae8-770c-4cd1-8ca8-c7f13bd7ba64"),
                            Name = "Николай Свечин"
                        },
                        new
                        {
                            Id = new Guid("5ac34184-f039-43da-8594-35e33c820882"),
                            Name = "Дмитрий Шелег"
                        },
                        new
                        {
                            Id = new Guid("b573b21d-544f-4072-a595-b427b54247a2"),
                            Name = "Джон Перкинс"
                        },
                        new
                        {
                            Id = new Guid("a9cfc2d7-f079-4205-8750-c48acbd2f231"),
                            Name = "Себастьян Жондо"
                        });
                });

            modelBuilder.Entity("DAL.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GenreName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBooking")
                        .HasColumnType("bit");

                    b.Property<string>("SubTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d23f2ec-2b54-4dd9-b52b-b7c83a23dd0a"),
                            AuthorId = new Guid("ff9b30ce-ad2e-48ce-b811-e45481b55043"),
                            AuthorName = "Жафаров Ильнур",
                            GenreId = new Guid("da589ab3-c70c-4d96-9ea9-867fedea69ff"),
                            GenreName = "Фантастика",
                            IsBooking = false,
                            SubTitle = "Там ересь была",
                            Text = "Ваха 40к",
                            Title = "Ересь Хоруса",
                            TitleImagePath = "1655641005121914702.jpg"
                        },
                        new
                        {
                            Id = new Guid("b2566eb6-2108-46ad-bc5f-b3a660d60d1b"),
                            AuthorId = new Guid("c07ada61-d847-43eb-b2eb-8e32adcd64f4"),
                            AuthorName = "Букин Генадий",
                            GenreId = new Guid("da589ab3-c70c-4d96-9ea9-867fedea69ff"),
                            GenreName = "Фантастика",
                            IsBooking = false,
                            SubTitle = "Там тоже была ересь",
                            Text = "Ваха 40к",
                            Title = "Ересь Хоруса: История Ангрона",
                            TitleImagePath = "1655641009118970804.jpg"
                        },
                        new
                        {
                            Id = new Guid("f59c2a21-0f24-469a-b7cc-495146124310"),
                            AuthorId = new Guid("ebcbdb38-9d81-4cba-9f6b-b0edb5d6bffa"),
                            AuthorName = "Уильям Голдинг",
                            GenreId = new Guid("79500809-b481-49a6-aeb6-869b86f9901e"),
                            GenreName = "Мировая классика",
                            IsBooking = false,
                            SubTitle = "История о мальчиках на острове",
                            Text = "Муха делает ж-ж-ж-ж-ж-ж-ж-ж-ж-ж",
                            Title = "Повелитель мух",
                            TitleImagePath = "119029-uilyam-golding-povelitel-muh-119029.webp"
                        },
                        new
                        {
                            Id = new Guid("ba99c9bb-23fb-4238-8491-f11101b8b6fa"),
                            AuthorId = new Guid("e5c68c75-9b15-4424-b062-b91c7f4b6332"),
                            AuthorName = "Габриэль Гарсиа",
                            GenreId = new Guid("79500809-b481-49a6-aeb6-869b86f9901e"),
                            GenreName = "Мировая классика",
                            IsBooking = false,
                            SubTitle = "Про патриарха осенью",
                            Text = "Что такое осень...",
                            Title = "Осень патриарха",
                            TitleImagePath = "119586-gabriel-garsia-markes-44998-osen-patriarha.webp"
                        },
                        new
                        {
                            Id = new Guid("814f9c1c-9fef-42ba-acbe-857e234f31a8"),
                            AuthorId = new Guid("4f91476b-4021-4581-b729-78c8fede5d3f"),
                            AuthorName = "Дмитрий Глуховский",
                            GenreId = new Guid("da589ab3-c70c-4d96-9ea9-867fedea69ff"),
                            GenreName = "Фантастика",
                            IsBooking = false,
                            SubTitle = "Про метро",
                            Text = "Классика вселенной метро",
                            Title = "Метро 2033",
                            TitleImagePath = "128391-dmitriy-gluhovskiy-metro-2033.webp"
                        },
                        new
                        {
                            Id = new Guid("629555f5-a728-4d49-b9c5-754e06c5baef"),
                            AuthorId = new Guid("9c37a892-1e81-4120-b8be-de6833215e67"),
                            AuthorName = "Василий Орехов",
                            GenreId = new Guid("da589ab3-c70c-4d96-9ea9-867fedea69ff"),
                            GenreName = "Фантастика",
                            IsBooking = false,
                            SubTitle = "Сталкер",
                            Text = "Классика вселенной сталкер",
                            Title = "Зона поражения",
                            TitleImagePath = "152893-vasiliy-orehov-zona-porazheniya.webp"
                        },
                        new
                        {
                            Id = new Guid("e895336e-deb2-4a70-a5b6-38cbd1501507"),
                            AuthorId = new Guid("d695cfa5-04cd-40ac-b0d7-307a8a876860"),
                            AuthorName = "Андрей Левицкий",
                            GenreId = new Guid("da589ab3-c70c-4d96-9ea9-867fedea69ff"),
                            GenreName = "Фантастика",
                            IsBooking = false,
                            SubTitle = "Сталкер",
                            Text = "Классика вселенной сталкер",
                            Title = "Сердце зоны",
                            TitleImagePath = "165057-andrey-levickiy-serdce-zony.webp"
                        },
                        new
                        {
                            Id = new Guid("ebb65c65-bac4-4215-8c4b-dcda8faa6e25"),
                            AuthorId = new Guid("fa10b14c-e352-4eac-91ae-982cb3fd3982"),
                            AuthorName = "Роман Глушков",
                            GenreId = new Guid("da589ab3-c70c-4d96-9ea9-867fedea69ff"),
                            GenreName = "Фантастика",
                            IsBooking = false,
                            SubTitle = "Сталкер",
                            Text = "Классика вселенной сталкер",
                            Title = "Свинцовый закат",
                            TitleImagePath = "172514-roman-glushkov-svincovyy-zakat-172514.webp"
                        },
                        new
                        {
                            Id = new Guid("1cb4916a-5755-4784-bed0-a69db6311504"),
                            AuthorId = new Guid("33a9c3e4-be82-40dd-8c06-4f29b0ac732a"),
                            AuthorName = "Захар Петров",
                            GenreId = new Guid("da589ab3-c70c-4d96-9ea9-867fedea69ff"),
                            GenreName = "Фантастика",
                            IsBooking = false,
                            SubTitle = "Про метро",
                            Text = "Классика вселенной метро",
                            Title = "Муос",
                            TitleImagePath = "3748275-zahar-petrov-muos.webp"
                        },
                        new
                        {
                            Id = new Guid("058b6f8f-b5c6-4b4f-9124-2c213cb3edfa"),
                            AuthorId = new Guid("2acdaae8-d1ce-4995-bc07-537f77cc74bc"),
                            AuthorName = "Айн Рэнд",
                            GenreId = new Guid("79500809-b481-49a6-aeb6-869b86f9901e"),
                            GenreName = "Мировая классика",
                            IsBooking = false,
                            SubTitle = "Про атланта",
                            Text = "Ну там то про то, то про это",
                            Title = "Атлант расправил плечи",
                            TitleImagePath = "4236675-ayn-rend-atlant-raspravil-plechi.webp"
                        },
                        new
                        {
                            Id = new Guid("8236e6e4-f03c-48ff-849a-a1e7d0d48cae"),
                            AuthorId = new Guid("bb1a20f6-4406-4fe3-bf82-b3b31453667b"),
                            AuthorName = "Стивен Кинг",
                            GenreId = new Guid("e4ac715f-a600-4d01-8a09-5439c7b689b3"),
                            GenreName = "Хоррор",
                            IsBooking = false,
                            SubTitle = "Про изоляцию людей под куполом",
                            Text = "Я ожидал большего от книги, честно говоря",
                            Title = "Под куполом",
                            TitleImagePath = "4387285-stiven-king-pod-kupolom.webp"
                        },
                        new
                        {
                            Id = new Guid("e89bd603-cda2-4bad-94d7-68862640a58d"),
                            AuthorId = new Guid("bb1a20f6-4406-4fe3-bf82-b3b31453667b"),
                            AuthorName = "Стивен Кинг",
                            GenreId = new Guid("e4ac715f-a600-4d01-8a09-5439c7b689b3"),
                            GenreName = "Хоррор",
                            IsBooking = false,
                            SubTitle = "Про башню наверн",
                            Text = "Ну там Рендал Флегг есть",
                            Title = "Темная башня",
                            TitleImagePath = "4887784-stiven-king-temnaya-bashnya.webp"
                        },
                        new
                        {
                            Id = new Guid("1b12fa4b-ad1a-45e1-ba9a-c67ea054e317"),
                            AuthorId = new Guid("afe48adb-b2a8-4d40-aef2-2816ec837304"),
                            AuthorName = "Валентин Катаев",
                            GenreId = new Guid("79500809-b481-49a6-aeb6-869b86f9901e"),
                            GenreName = "Мировая классика",
                            IsBooking = false,
                            SubTitle = "Про мальчика",
                            Text = "В полке мальчик был",
                            Title = "Сын полка",
                            TitleImagePath = "8217563-valentin-kataev-syn-polka-8217563.webp"
                        },
                        new
                        {
                            Id = new Guid("45723e77-c301-4ac5-b6bc-2f5561fe453e"),
                            AuthorId = new Guid("bb1a20f6-4406-4fe3-bf82-b3b31453667b"),
                            AuthorName = "Стивен Кинг",
                            GenreId = new Guid("e4ac715f-a600-4d01-8a09-5439c7b689b3"),
                            GenreName = "Хоррор",
                            IsBooking = false,
                            SubTitle = "Вот нашел, забрал себе",
                            Text = "Вроде норм, не читал",
                            Title = "Кто нашел, берет себе",
                            TitleImagePath = "12483328-stiven-king-kto-nashel-beret-sebe-12483328.webp"
                        },
                        new
                        {
                            Id = new Guid("c0a214e6-aa17-40ad-90fe-e1f465022102"),
                            AuthorId = new Guid("bb1a20f6-4406-4fe3-bf82-b3b31453667b"),
                            AuthorName = "Стивен Кинг",
                            GenreId = new Guid("e4ac715f-a600-4d01-8a09-5439c7b689b3"),
                            GenreName = "Хоррор",
                            IsBooking = false,
                            SubTitle = "Про киллера",
                            Text = "Аудиокнига у Булдакова еще не вышла, а печатную читать нет времени",
                            Title = "Билли Саммерс",
                            TitleImagePath = "67303161-stiven-king-billi-sammers.webp"
                        },
                        new
                        {
                            Id = new Guid("893ed244-ed74-4618-b101-3e88b726d128"),
                            AuthorId = new Guid("a40e7075-54fc-4015-9488-1b32652b96e4"),
                            AuthorName = "Олдос Хаксли",
                            GenreId = new Guid("79500809-b481-49a6-aeb6-869b86f9901e"),
                            GenreName = "Мировая классика",
                            IsBooking = false,
                            SubTitle = "Это шедевр!!!",
                            Text = "Книга в свое время перевернувшая мое представление о совершенном мире",
                            Title = "О дивный новый мир",
                            TitleImagePath = "14332383-oldos-leonard-haksli-o-divnyy-novyy-mir.webp"
                        },
                        new
                        {
                            Id = new Guid("ba3af0e2-6a4c-4070-aa0c-0ffc0027d60f"),
                            AuthorId = new Guid("a6ffa373-2b5a-424e-b5ed-835678fd0d92"),
                            AuthorName = "Джордж Оруэл",
                            GenreId = new Guid("79500809-b481-49a6-aeb6-869b86f9901e"),
                            GenreName = "Мировая классика",
                            IsBooking = false,
                            SubTitle = "Книга о дескридетирующая коммунистический строй",
                            Text = "Неплохо",
                            Title = "Скотный двор",
                            TitleImagePath = "19258232--.webp"
                        },
                        new
                        {
                            Id = new Guid("0b6dbc1a-0ab8-4e00-b620-bf517abe8789"),
                            AuthorId = new Guid("7785baef-d027-4c00-be4f-237846c9c318"),
                            AuthorName = "Артур Конан Дойл",
                            GenreId = new Guid("c500c41b-6b66-424b-b8d8-bf88e8f76a9e"),
                            GenreName = "Детектив",
                            IsBooking = false,
                            SubTitle = "Классический детектив",
                            Text = "Неплохо",
                            Title = "Шерлок Холмс",
                            TitleImagePath = "23571677-arthur-konan-doyle-ves-sherlok-holms.webp"
                        },
                        new
                        {
                            Id = new Guid("85b7a108-6e59-43ec-946f-39baf40d49fe"),
                            AuthorId = new Guid("65b1fd9e-36d4-4965-bd3f-66a3e4859426"),
                            AuthorName = "Наиль Выборнов",
                            GenreId = new Guid("da589ab3-c70c-4d96-9ea9-867fedea69ff"),
                            GenreName = "Фантастика",
                            IsBooking = false,
                            SubTitle = "Про метро",
                            Text = "Классика вселенной метро",
                            Title = "Переход",
                            TitleImagePath = "23789586-nail-vybornov-metro-2033-perehod.webp"
                        },
                        new
                        {
                            Id = new Guid("9326fb09-8557-4cdf-a2e5-6a3cf65ff252"),
                            AuthorId = new Guid("ee09b74a-99ff-4f41-a04b-5957c2d8c3b6"),
                            AuthorName = "Эрих Мария Ремарк",
                            GenreId = new Guid("79500809-b481-49a6-aeb6-869b86f9901e"),
                            GenreName = "Мировая классика",
                            IsBooking = false,
                            SubTitle = "Про фронт книга",
                            Text = "Нет, не про фронэнд",
                            Title = "На западном фронте без перемен",
                            TitleImagePath = "32878920-erih-mariya-remark-na-zapadnom-fronte-bez-peremen-32878920.webp"
                        },
                        new
                        {
                            Id = new Guid("8638a5fa-e30d-41a0-9db2-1493d38044eb"),
                            AuthorId = new Guid("1198ab8d-59e8-4ce8-a4ee-98cce1f65eec"),
                            AuthorName = "Рей Брэдбери",
                            GenreId = new Guid("79500809-b481-49a6-aeb6-869b86f9901e"),
                            GenreName = "Мировая классика",
                            IsBooking = false,
                            SubTitle = "По сути книга про то, к чему стремится наша поп культура",
                            Text = "Мне не очень зашла",
                            Title = "451 градус по фарингейту",
                            TitleImagePath = "39507162--.webp"
                        },
                        new
                        {
                            Id = new Guid("c3922ccf-dcfa-4c35-90bc-cc9dbc5e8902"),
                            AuthorId = new Guid("a6ffa373-2b5a-424e-b5ed-835678fd0d92"),
                            AuthorName = "Джордж Оруэл",
                            GenreId = new Guid("79500809-b481-49a6-aeb6-869b86f9901e"),
                            GenreName = "Мировая классика",
                            IsBooking = false,
                            SubTitle = "Лучшее что я читал",
                            Text = "После себя оставляет ощущение опустошенности и безысходности",
                            Title = "1984",
                            TitleImagePath = "67281231--.webp"
                        },
                        new
                        {
                            Id = new Guid("50259038-7e6f-402e-a80a-4a85a9cf8afe"),
                            AuthorId = new Guid("3cbe84ba-9744-4cef-9dd9-815c7c53e133"),
                            AuthorName = "Сергей Лукьяненко",
                            GenreId = new Guid("87bbe432-9779-4488-a769-0c067a65aecd"),
                            GenreName = "Приключения",
                            IsBooking = false,
                            SubTitle = "Наверное про то как волотер провел лето",
                            Text = "Не читал, не знаю о чем она",
                            Title = "Лето волонтера",
                            TitleImagePath = "67385403-sergey-lukyanenko-leto-volontera.webp"
                        },
                        new
                        {
                            Id = new Guid("d0528761-f101-4f4f-b0fc-0a970a2026bd"),
                            AuthorId = new Guid("3f40c815-4d3f-42f7-92e8-10543306465f"),
                            AuthorName = "Алексей Гришин",
                            GenreId = new Guid("87bbe432-9779-4488-a769-0c067a65aecd"),
                            GenreName = "Приключения",
                            IsBooking = false,
                            SubTitle = "Типичный попаданец",
                            Text = "Конкретно эту не читал, но у попаданцев в целом 30/70 - хорошие/плохие книги",
                            Title = "Выбор из худшего",
                            TitleImagePath = "67891001-aleksey-grishin-vybor-iz-hudshego.webp"
                        },
                        new
                        {
                            Id = new Guid("19f4d611-5a6a-4cf1-bcde-02e85081bb18"),
                            AuthorId = new Guid("549ceae8-770c-4cd1-8ca8-c7f13bd7ba64"),
                            AuthorName = "Николай Свечин",
                            GenreId = new Guid("79500809-b481-49a6-aeb6-869b86f9901e"),
                            GenreName = "Мировая классика",
                            IsBooking = false,
                            SubTitle = "Российская классика",
                            Text = "Даже не знаю, чем они там могли заняться, с работы раньше ушли наверное...",
                            Title = "В отсутствие начальства",
                            TitleImagePath = "67922364-nikolay-svechin-v-otsutstvie-nachalstva.webp"
                        },
                        new
                        {
                            Id = new Guid("8fbc3dd1-8d19-454e-8aa3-a31749ea66be"),
                            AuthorId = new Guid("5ac34184-f039-43da-8594-35e33c820882"),
                            AuthorName = "Дмитрий Шелег",
                            GenreId = new Guid("c500c41b-6b66-424b-b8d8-bf88e8f76a9e"),
                            GenreName = "Детектив",
                            IsBooking = false,
                            SubTitle = "Один истинный, остальные ложные",
                            Text = "Ну там сначала ложный был, потом истинный появился",
                            Title = "Истинный князь",
                            TitleImagePath = "68010554-dmitriy-vitalevich-sheleg-istinnyy-knyaz.webp"
                        },
                        new
                        {
                            Id = new Guid("94271f11-d6b7-43a8-b516-1b0f78f5cf10"),
                            AuthorId = new Guid("b573b21d-544f-4072-a595-b427b54247a2"),
                            AuthorName = "Джон Перкинс",
                            GenreId = new Guid("008fb99c-c826-4ee2-bf89-e60f1ffaf6a9"),
                            GenreName = "Научная литература",
                            IsBooking = false,
                            SubTitle = "Про загнивающий запад",
                            Text = "Обэма во всем виноват",
                            Title = "Исповедь экономического убийцы",
                            TitleImagePath = "132973-dzhon-perkins-ispoved-ekonomicheskogo-ubiycy.webp"
                        },
                        new
                        {
                            Id = new Guid("213f74db-5ffd-4123-bd8c-e07c63c02c03"),
                            AuthorId = new Guid("a9cfc2d7-f079-4205-8750-c48acbd2f231"),
                            AuthorName = "Себастьян Жондо",
                            GenreId = new Guid("e5372338-ee97-408b-82c2-ab7e3ca6d145"),
                            GenreName = "Неизвестный жанр",
                            IsBooking = false,
                            SubTitle = "А как у него дела, кст?",
                            Text = "Я хз, он не говорит",
                            Title = "Как дела, дорогой Карл?",
                            TitleImagePath = "67985997-virzhini-muza-kak-dela-dorogoy-karl-otkrovennye-memuary-telohranitelya-kar.webp"
                        },
                        new
                        {
                            Id = new Guid("8c47f19c-a91e-4524-8004-220fa1734c25"),
                            AuthorId = new Guid("30254b73-712a-48d4-bf0b-412216a90ade"),
                            AuthorName = "Вячеслав Шалыгин",
                            GenreId = new Guid("da589ab3-c70c-4d96-9ea9-867fedea69ff"),
                            GenreName = "Фантастика",
                            IsBooking = false,
                            SubTitle = "Довольно неплохой тайтл по сталкеру",
                            Text = "В зоне зародилась новая аномалия",
                            Title = "Черный ангел",
                            TitleImagePath = "166136-vyacheslav-shalygin-chernyy-angel.webp"
                        });
                });

            modelBuilder.Entity("DAL.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BooksTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinishedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IssueBooking")
                        .HasColumnType("bit");

                    b.Property<string>("ReceiptCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("DAL.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("DAL.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("da589ab3-c70c-4d96-9ea9-867fedea69ff"),
                            Name = "Фантастика"
                        },
                        new
                        {
                            Id = new Guid("e4ac715f-a600-4d01-8a09-5439c7b689b3"),
                            Name = "Хоррор"
                        },
                        new
                        {
                            Id = new Guid("c500c41b-6b66-424b-b8d8-bf88e8f76a9e"),
                            Name = "Детектив"
                        },
                        new
                        {
                            Id = new Guid("87bbe432-9779-4488-a769-0c067a65aecd"),
                            Name = "Приключения"
                        },
                        new
                        {
                            Id = new Guid("79500809-b481-49a6-aeb6-869b86f9901e"),
                            Name = "Мировая классика"
                        },
                        new
                        {
                            Id = new Guid("008fb99c-c826-4ee2-bf89-e60f1ffaf6a9"),
                            Name = "Научная литература"
                        },
                        new
                        {
                            Id = new Guid("e5372338-ee97-408b-82c2-ab7e3ca6d145"),
                            Name = "Неизвестный жанр"
                        });
                });

            modelBuilder.Entity("DAL.Domain.Entities.TextField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TextFields");

                    b.HasData(
                        new
                        {
                            Id = new Guid("63dc8fa6-07ae-4391-8916-e057f71239ce"),
                            CodeWord = "PageIndex",
                            Text = "<h2>Добро пожаловать в нашу библиотеку</h2><p>Эта <strong>Библиотека</strong> лучшая в мире и это не только мое мнение. Наша задача сделать литературу доступной для всех желающих. Предлагаем вам пройти регистрацию и начать пользоваться</p>",
                            Title = "Главная"
                        },
                        new
                        {
                            Id = new Guid("70bf165a-700a-4156-91c0-e83fce0a277f"),
                            CodeWord = "PageBooks",
                            Text = "Сейчас здесь пусто, содержание заполняется администратором",
                            Title = "Книги"
                        },
                        new
                        {
                            Id = new Guid("4aa76a4c-c59d-409a-84c1-06e6487a137a"),
                            CodeWord = "PageContacts",
                            Text = "<h2>Мои контакты</h2><p>Почта: cr.xeller@mail.ru</p><p>Телеграм: @NikitaGitNet</p>",
                            Title = "Контакты"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8af10569-b018-4fe7-a380-7d6a14c70b74",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "5e84bf2c-585f-42dc-a868-73157016ec70",
                            Name = "moderator",
                            NormalizedName = "MODERATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3b62472e-4f66-49fa-a20f-e7685b9565d8",
                            RoleId = "8af10569-b018-4fe7-a380-7d6a14c70b74"
                        },
                        new
                        {
                            UserId = "86d55f40-9544-4d92-aa24-cc5693a5fd96",
                            RoleId = "5e84bf2c-585f-42dc-a868-73157016ec70"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DAL.Domain.Entities.Book", b =>
                {
                    b.HasOne("DAL.Domain.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Domain.Entities.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("DAL.Domain.Entities.Booking", b =>
                {
                    b.HasOne("DAL.Domain.Entities.Book", "Book")
                        .WithMany("Bookings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Domain.Entities.Comment", b =>
                {
                    b.HasOne("DAL.Domain.Entities.Book", "Book")
                        .WithMany("Comments")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DAL.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DAL.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DAL.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("DAL.Domain.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Domain.Entities.Book", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("DAL.Domain.Entities.Genre", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
